version: '3'
services:
  deviltea-io-backend:
    container_name: 'deviltea-io-backend'
    hostname: 'deviltea-io-backend'
    build: .
    command: sh -c "/wait && yarn build && yarn start:docker"
    volumes:
      - .:/usr/src/app/
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 8787:8787
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      WAIT_HOSTS: redis:6379, mongo:27017
      WAIT_HOSTS_TIMEOUT: 60
    external_links:
      - localhost
  redis:
    image: redis
    container_name: 'redis'
    hostname: 'redis'
    ports:
      - 6379:6379
  mongo:
    image: mongo
    container_name: 'mongo'
    hostname: 'mongo'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongodb/setup.js:/docker-entrypoint-initdb.d/setup.js:ro
      - ./data/mongodb/db:/data/db
